# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Create Similarity Matrix
#' @description Constructs a similarity matrix comparing all points clustering across the 
#' iterations.
#' @param samples Matrix of label assignment for data across iterations.
#' @return A symmetric n x n matrix (for n rows in cluster record) describing 
#' the fraction of samples for which each pairwise combination of points are
#' assigned the same label.
#' @export
createSimilarityMat <- function(samples) {
    .Call(`_ccbm_createSimilarityMat`, samples)
}

#' @title The Beta Distribution
#' @description Random generation from the Beta distribution. 
#' See https://en.wikipedia.org/wiki/Beta_distribution#Related_distributions.
#' Samples from a Beta distribution based using two independent gamma 
#' distributions. 
#' @param a Shape parameter.
#' @param b Shape parameter.
#' @return Sample from Beta(a, b).
NULL

#' @title The Beta Distribution
#' @description Random generation from the Beta distribution. 
#' See https://en.wikipedia.org/wiki/Beta_distribution#Related_distributions.
#' Samples from a Beta distribution based using two independent gamma 
#' distributions. 
#' @param n The number of samples to draw.
#' @param a Shape parameter.
#' @param b Shape parameter.
#' @return Sample from Beta(a, b).
NULL

#' @title Calculate sample covariance
#' @description Returns the unnormalised sample covariance. Required as 
#' arma::cov() does not work for singletons.
#' @param data Data in matrix format
#' @param sample_mean Sample mean for data
#' @param n The number of samples in data
#' @param n_col The number of columns in data
#' @return One of the parameters required to calculate the posterior of the
#'  Multivariate normal with uknown mean and covariance (the unnormalised 
#'  sample covariance).
NULL

#' @name sampler
#' @title Generic mixture type
#' @description The class that the specific sampler types inherit from. Used as
#' the generic mixture type.
#' @field new Constructor \itemize{
#' \item Parameter: K - the number of components to model
#' \item Parameter: labels - the initial clustering of the data
#' \item Parameter: concentration - the vector for the prior concentration of
#' the Dirichlet distribution of the component weights
#' \item Parameter: X - the data to model
#' }
#' @field printType Print the sampler type called.
#' @field updateWeights Update the weights of each component based on current
#' clustering.
#' @field updateAllocation Sample a new clustering.
#' @field sampleFromPrior Virtual placeholder for sampling from the priors of
#' the specific mixtures.
#' @field calcBIC Virtual placeholder for the function that calculates the BIC
#' of specific mixture models.
#' @field logLikelihood Virtual placeholder for the function that calculates
#' the likelihood of a given point in each component of specific mixture models.
NULL

#' @name gaussianSampler
#' @title Gaussian mixture type
#' @description The sampler for a mixture of Gaussians, where each feature is
#' assumed to be independent (i.e. a multivariate Normal with a diagonal 
#' covariance matrix).
#' @field new Constructor \itemize{
#' \item Parameter: K - the number of components to model
#' \item Parameter: labels - the initial clustering of the data
#' \item Parameter: concentration - the vector for the prior concentration of 
#' the Dirichlet distribution of the component weights
#' \item Parameter: X - the data to model
#' }
#' @field printType Print the sampler type called.
#' @field updateWeights Update the weights of each component based on current 
#' clustering.
#' @field updateAllocation Sample a new clustering. 
#' @field sampleFromPrior Sample from the priors for the Gaussian density.
#' @field calcBIC Calculate the BIC of the model.
#' @field logLikelihood Calculate the likelihood of a given data point in each
#' component. \itemize{
#' \item Parameter: point - a data point.
#' }
NULL

#' @name mvnSampler
#' @title Multivariate Normal mixture type
#' @description The sampler for the Multivariate Normal mixture model.
#' @field new Constructor \itemize{
#' \item Parameter: K - the number of components to model
#' \item Parameter: labels - the initial clustering of the data
#' \item Parameter: concentration - the vector for the prior concentration of 
#' the Dirichlet distribution of the component weights
#' \item Parameter: X - the data to model
#' }
#' @field printType Print the sampler type called.
#' @field updateWeights Update the weights of each component based on current 
#' clustering.
#' @field updateAllocation Sample a new clustering. 
#' @field sampleFromPrior Sample from the priors for the multivariate normal
#' density.
#' @field calcBIC Calculate the BIC of the model.
#' @field logLikelihood Calculate the likelihood of a given data point in each
#' component. \itemize{
#' \item Parameter: point - a data point.
#' }
NULL

#' @name categoricalSampler
#' @title Categorical mixture type
#' @description The sampler for the Categorical mixture model.
#' @field new Constructor \itemize{
#' \item Parameter: K - the number of components to model
#' \item Parameter: labels - the initial clustering of the data
#' \item Parameter: concentration - the vector for the prior concentration of 
#' the Dirichlet distribution of the component weights
#' \item Parameter: X - the data to model
#' }
#' @field printType Print the sampler type called.
#' @field updateWeights Update the weights of each component based on current 
#' clustering.
#' @field updateAllocation Sample a new clustering. 
#' @field sampleFromPrior Sample from the priors for the Categorical density.
#' @field calcBIC Calculate the BIC of the model.
#' @field logLikelihood Calculate the likelihood of a given data point in each
#' component. \itemize{
#' \item Parameter: point - a data point.
#' }
NULL

#' @name tAdjustedSampler
#' @title Base class for adding a t-distribution to sweep up outliers in the 
#' model.
#' @description The class that the specific TAGM types inherit from. 
#' @field new Constructor \itemize{
#' \item Parameter: K - the number of components to model
#' \item Parameter: labels - the initial clustering of the data
#' \item Parameter: concentration - the vector for the prior concentration of 
#' the Dirichlet distribution of the component weights
#' \item Parameter: X - the data to model
#' }
#' @field updateOutlierWeights Updates the weight of the outlier component.
#' @field updateWeights Update the weights of each component based on current 
#' clustering, excluding the outliers.
#' @field sampleOutlier Sample is the nth item is an outlier. \itemize{
#' \item Parameter n: the index of the individual in the data matrix and 
#' allocation vector.
#' }
#' @field updateAllocation Sample a new clustering and simultaneously allocate 
#' items to the outlier distribution.
#' @field calcTdistnLikelihood Virtual placeholder for the function that calculates 
#' the likelihood of a given point in a t-distribution. \itemize{
#' \item Parameter: point - a data point.
#' }
NULL

#' @name tagmMVN
#' @title T-ADjusted Gaussian Mixture (TAGM) type
#' @description The sampler for the TAGM mixture model.
#' @field new Constructor \itemize{
#' \item Parameter: K - the number of components to model
#' \item Parameter: labels - the initial clustering of the data
#' \item Parameter: concentration - the vector for the prior concentration of 
#' the Dirichlet distribution of the component weights
#' \item Parameter: X - the data to model
#' }
#' @field printType Print the sampler type called.
#' @field calcBIC Calculate the BIC of the model.
#' @field calcTdistnLikelihood Calculate the likelihood of a given data point 
#' the gloabl t-distirbution. \itemize{
#' \item Parameter: point - a data point.
#' }
NULL

#' @name tagmGaussian
#' @title T-ADjusted Gaussian Mixture (TAGM) type
#' @description The sampler for the TAGM mixture model with assumption of 
#' independent features.
#' @field new Constructor \itemize{
#' \item Parameter: K - the number of components to model
#' \item Parameter: labels - the initial clustering of the data
#' \item Parameter: concentration - the vector for the prior concentration of 
#' the Dirichlet distribution of the component weights
#' \item Parameter: X - the data to model
#' }
#' @field printType Print the sampler type called.
#' @field calcBIC Calculate the BIC of the model.
#' @field calcTdistnLikelihood Calculate the likelihood of a given data point 
#' the gloabl t-distribution. \itemize{
#' \item Parameter: point - a data point.
#' }
NULL

#' @name samplerFactory
#' @title Factory for different sampler subtypes.
#' @description The factory allows the type of mixture implemented to change 
#' based upon the user input.
#' @field new Constructor \itemize{
#' \item Parameter: samplerType - the density type to be modelled
#' \item Parameter: K - the number of components to model
#' \item Parameter: labels - the initial clustering of the data
#' \item Parameter: concentration - the vector for the prior concentration of 
#' the Dirichlet distribution of the component weights
#' \item Parameter: X - the data to model
#' }
NULL

#' @name samplerFactory
#' @title Factory for different sampler subtypes.
#' @description The factory allows the type of mixture implemented to change 
#' based upon the user input.
#' @field new Constructor \itemize{
#' \item Parameter: samplerType - the density type to be modelled
#' \item Parameter: K - the number of components to model
#' \item Parameter: labels - the initial clustering of the data
#' \item Parameter: concentration - the vector for the prior concentration of 
#' the Dirichlet distribution of the component weights
#' \item Parameter: X - the data to model
#' }
NULL

#' @title Mixture model
#' @description Performs MCMC sampling for a mixture model.
#' @param X The data matrix to perform clustering upon (items to cluster in rows).
#' @param K The number of components to model (upper limit on the number of clusters found).
#' @param labels Vector item labels to initialise from.
#' @param dataType Int, 0: independent Gaussians, 1: Multivariate normal, or 2: Categorical distributions.
#' @param R The number of iterations to run for.
#' @param thin thinning factor for samples recorded.
#' @param concentration Vector of concentrations for mixture weights (recommended to be symmetric).
#' @return Named list of the matrix of MCMC samples generated (each row 
#' corresponds to a different sample) and BIC for each saved iteration.
sampleMixtureModel <- function(X, K, labels, dataType, R, thin, concentration, seed) {
    .Call(`_ccbm_sampleMixtureModel`, X, K, labels, dataType, R, thin, concentration, seed)
}

#' @title Mixture model
#' @description Performs MCMC sampling for a mixture model.
#' @param X The data matrix to perform clustering upon (items to cluster in rows).
#' @param K The number of components to model (upper limit on the number of clusters found).
#' @param labels Vector item labels to initialise from.
#' @param fixed Binary vector of the items that are fixed in their initial label.
#' @param dataType Int, 0: independent Gaussians, 1: Multivariate normal, or 2: Categorical distributions.
#' @param R The number of iterations to run for.
#' @param thin thinning factor for samples recorded.
#' @param concentration Vector of concentrations for mixture weights (recommended to be symmetric).
#' @return Named list of the matrix of MCMC samples generated (each row 
#' corresponds to a different sample) and BIC for each saved iteration.
sampleSemisupervisedMixtureModel <- function(X, K, labels, fixed, dataType, R, thin, concentration, seed) {
    .Call(`_ccbm_sampleSemisupervisedMixtureModel`, X, K, labels, fixed, dataType, R, thin, concentration, seed)
}

