# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Create Similarity Matrix
#' @description Constructs a similarity matrix comparing all points clustering across the 
#' iterations.
#' @param samples Matrix of label assignment for data across iterations.
#' @return A symmetric n x n matrix (for n rows in cluster record) describing 
#' the fraction of samples for which each pairwise combination of points are
#' assigned the same label.
#' @export
createSimilarityMat <- function(samples) {
    .Call(`_ccbm_createSimilarityMat`, samples)
}

#' @title The Beta Distribution
#' @description Random generation from the Beta distribution. 
#' See https://en.wikipedia.org/wiki/Beta_distribution#Related_distributions.
#' Samples from a Beta distribution based using two independent gamma 
#' distributions. 
#' @param a Shape parameter.
#' @param b Shape parameter.
#' @return Sample from Beta(a, b).
NULL

#' @title The Beta Distribution
#' @description Random generation from the Beta distribution. 
#' See https://en.wikipedia.org/wiki/Beta_distribution#Related_distributions.
#' Samples from a Beta distribution based using two independent gamma 
#' distributions. 
#' @param n The number of samples to draw.
#' @param a Shape parameter.
#' @param b Shape parameter.
#' @return Sample from Beta(a, b).
NULL

#' @title Calculate sample covariance
#' @description Returns the unnormalised sample covariance. Required as 
#' arma::cov() does not work for singletons.
#' @param data Data in matrix format
#' @param sample_mean Sample mean for data
#' @param n The number of samples in data
#' @param n_col The number of columns in data
#' @return One of the parameters required to calculate the posterior of the
#'  Multivariate normal with uknown mean and covariance (the unnormalised 
#'  sample covariance).
NULL

#' @title Mixture model
#' @description Performs MCMC sampling for a mixture model.
#' @param X The data matrix to perform clustering upon (items to cluster in rows).
#' @param K The number of components to model (upper limit on the number of clusters found).
#' @param labels Vector item labels to initialise from.
#' @param dataType Int, 0: independent Gaussians, 1: Multivariate normal, or 2: Categorical distributions.
#' @param R The number of iterations to run for.
#' @param thin thinning factor for samples recorded.
#' @param concentration Vector of concentrations for mixture weights (recommended to be symmetric).
#' @return Named list of the matrix of MCMC samples generated (each row 
#' corresponds to a different sample) and BIC for each saved iteration.
sampleMixtureModel <- function(X, K, labels, dataType, R, thin, concentration, seed) {
    .Call(`_ccbm_sampleMixtureModel`, X, K, labels, dataType, R, thin, concentration, seed)
}

